### ISSUE TITLE
The "New Topic" button is greyed-out

### ISSUE THREAD

**Issue by sylque** [sylque/discpage#32]
_Originally posted by @noobishme in https://github.com/sylque/discpage/issues/30#issuecomment-1246046383_

The **+ New Topic** button is greyed-out and unclickable.

![Screenshot 2022-09-13 171341](https://user-images.githubusercontent.com/106134379/190026168-89c94a41-7551-423b-9cf4-431ec99479bc.png)

**Comment by sylque** [comment]
Good catch.

Please install DiscPage v1.0.52 and let me know if it's fixed.

**Comment by noobishme** [comment]
Yay - you fixed this!  Many thanks!!!

![Screenshot 2022-09-14 113714](https://user-images.githubusercontent.com/106134379/190224500-d349866a-1f80-42e1-b72a-bc03b727fdad.png)

![Screenshot 2022-09-14 113744](https://user-images.githubusercontent.com/106134379/190224525-687341d1-e245-4e85-bfaf-96d575c6b73c.png)

**Comment by sylque** [comment]
Fixed in  v1.0.52
