### ISSUE TITLE
Posts may not display correctly because one of the post content decorators.

### ISSUE THREAD

**Issue by zebracasket** [sylque/discpage#40]
Was working great until today and doing a rebuild.  Getting this error and red hamburger menu without On/Off and unable to alt+a.  Seem youtube embed's also are now unable to play on page and link directory to the video on youtube's site.  Don't know if that is related to this though.  

 1.0.58 and 3.3.0.beta2-dev
([9b829216b2](https://github.com/discourse/discourse/commits/9b829216b259838e9bb896e8364868b81cb67891)
)

<img width="848" alt="discpage_error_042824" src="https://github.com/sylque/discpage/assets/146045277/50c24fcc-506b-4222-b742-5c214f56b744">

**Comment by sylque** [comment]
Thanks for reporting, I will have a look in the coming 48 hours.

**Comment by sylque** [comment]
@zebracasket , I could indeed get the "Posts may not display correctly" banner when adding a YouTube video. However, I couldn't reproduce the "red hamburger menu without On/Off" issue. I've deployed a new version (1.0.59) with a fix, please tell me if it works. Please also update your Discourse to the latest version. Thanks.

**Comment by zebracasket** [comment]
Looks like that did the trick.  I have two instances running and, only one is giving me the red hamburger menu without On/Off" issue, which makes me think its more of an isolated issue I need to fix myself.  But the updates across the plugina nd the newest discourse is working great.  Youtube is playing as expected as well!
