### ISSUE TITLE
help! styling trouble

### ISSUE THREAD

**Issue by giovanibee** [sylque/discpage#7]
hi! i'm a discourse/general newb person, and uh, i was wondering how to style individual and general static pages? I'm clearly doing something wrong here.

some things i tried under the style/script/html/head tags:
```
`html[data-type='data-dpg-page-id'] {
   background: red;
}`

$(html.dpg-page-content).css({
   background: red;
});

var ugh = document.getElementByClass("html.dpg-page-content");
ugh.css({
   background: red;
});

console.log("come on plz work plz just turn the background red plz");
```

sooo I was wondering if there was a clear example to styling pages? also under the script, nothing shows, not even a console.log() call on the console...log.

**Comment by sylque** [comment]
Hi @giovanibee,
I've improved the doc [here](https://github.com/sylque/discpage/blob/master/README.md#static-pages). To know more about styling in general, you can have a look at [this page](https://meta.discourse.org/t/beginners-guide-to-using-discourse-themes/91966). Please let me know if you have any more questions.

**Comment by giovanibee** [comment]
awesome! thank you!!! that basically answers all my life's questions. i can sleep peacefully now.
