### ISSUE TITLE
 Invalid Discourse setting "tagging enabled": must be set to true

### ISSUE THREAD

**Issue by limenleap** [sylque/discpage#9]
Discpage plugin is giving this error: _DiscPage Error - Invalid Discourse setting "tagging enabled": must be set to true_ 
I have enalbed tagging (from what I could make out) but the error does not go away...
and possibly due to that, it is turning the Hamburger menu red. I am on the latest installation as on this date. 
Discpage version is 1.0.32
Discourse is 2.6.0.beta1

**Comment by sylque** [comment]
Yes, the hamburger menu is red because of the error. 
However, the error itself looks weird. Are you sure tagging is enabled? (can you load the /tags page?) 
Is your Discourse instance a public instance I can access?

**Comment by limenleap** [comment]
I figured it out. Yes the settings tagging was not enabled. Pardon me. You can close this
